### ISSUE TITLE
Suggestion: Tap to reveal as an alternative to long-press

### ISSUE THREAD

**Issue by mcaubrey** [oguzgelal/juken#35]
I'd much rather just tap the card (anywhere on the card) to reveal it rather than having to long-press each time.

**Comment by oguzgelal** [comment]
Thanks for the feedback! I'll add this this to the next version.

**Comment by oguzgelal** [comment]
- [ ] Option to set the trigger area to the entire card vs. only the button
- [ ] Option to enable / disable long press
- [ ] Option to enable / disable haptic feedback

**Comment by oguzgelal** [comment]
This is implemented, and will be included in the upcoming release
