### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by elementart** [oguzgelal/juken#49]
My eyes beg you

**Comment by oguzgelal** [comment]
@elementart Understandable! :) I'll add this ticket to the roadmap. Thanks for the feedback!

**Comment by asutekku** [comment]
Implemented here: https://github.com/oguzgelal/juken/pull/53

**Comment by oguzgelal** [comment]
@asutekku The dark mode looks amazing! I just added a toggle for it, I'll roll it out today.
