### ISSUE TITLE
"Answer without revealing" not working on web

### ISSUE THREAD

**Issue by MhmdFVC** [oguzgelal/juken#59]
Firefox 78.0.2 64-bit for Windows 10, using NoScript and uBlock Origin but I've allowed everything except Google Analytics/Tag Manager and disabled uBlock for the page. 

The first card I get seems to work fine, but if I try passing any cards afterward without revealing them, they just come back after the animation and won't let me continue to the next one unless I reveal the meaning/reading.

**Comment by tiagoben** [comment]
Sent pull request to fix this bug

**Comment by oguzgelal** [comment]
@tiagoben Awesome, thanks you so much! Today I'll give it a test run and merge :)

**Comment by oguzgelal** [comment]
It's merged https://github.com/oguzgelal/juken/pull/62
