### ISSUE TITLE
Juken down?

### ISSUE THREAD

**Issue by midse** [oguzgelal/juken#63]
![image](https://user-images.githubusercontent.com/7143508/90242608-4db69d80-de68-11ea-956b-3aa37d732a1d.png)

**Comment by oguzgelal** [comment]
Oh this seems like an issue from yesterday's push, I'll take a quick look, seems like an easy fix

**Comment by oguzgelal** [comment]
@midse Just what I thought, I pushed a fix [here](https://github.com/oguzgelal/juken/pull/64), should be live in a few minutes. Thanks for reporting!

**Comment by midse** [comment]
Up and running again! Thanks for the quick fix.
