### ISSUE TITLE
Last letter of words cut off

### ISSUE THREAD

**Issue by Kev-9** [oguzgelal/juken#67]
When first logging in, the login button is shown as "Logi" and the more button is shown as "Mor".

On the actual flash cards words only show up as "Vocabular", "Readin", "Revea" etc.

The actual answers show up the same way when revealed (e.g. answer for 今 is shown as "No" instead of "Now").

Also, some answers seem to get cut off as well sometimes. If the Kanji has multiple meanings, only the first (few) English word(s) are shown sometimes. If that's the case, there's a comma after the words that do show up but no word following the comma.

Everything surrounding the flash cards is fine ("Reviews" on top, "Reviews" and "Cards" on the bottom). The menu shows up fine as well.

I'm using a OnePlus 6t

![Screenshot_20200826-214816.jpg](https://user-images.githubusercontent.com/29470670/91349662-e85a9900-e7e5-11ea-8339-cabd6cd90756.jpg)

**Comment by oguzgelal** [comment]
That's really odd. I'll investigate this. Thanks for reporting!

**Comment by Kev-9** [comment]
Quick update: Just encountered the same issue with another app and it seems it's to do with [React Native and the OnePlus Slate font](https://forums.expo.io/t/text-cut-off-on-oneplus-device/4999). Changing the font in my phone's settings to Roboto seems to have fixed it for both apps.

**Comment by oguzgelal** [comment]
@Kev-9 I see, sorry couldn't have time to investigate this yet but from what you said it sounds like it's a font issue unrelated to Juken. I'll close this for now but feel free to reopen if needed.

**Comment by Kev-9** [comment]
No worries, wasn't too bad and I've got a solution now.

It's not directly related to Juken but it might not be completely unrelated either though. 
I only had a quick read-through but there are some [suggestions](https://forums.expo.io/t/text-cut-off-on-oneplus-device/4999/5) to fix this in the app itself (_by changing the app font; by adding a double space after text instead of single space. Use template literals of react. {’ '}_). 

No need to bother fixing this if nobody else has this issue though, so closing it is fine by me.

Thanks!
